#!/bin/sh

case "$1" in
  start)
    rm -rf /data/frp/log.txt
    chmod 755 /data/frp/*
    /data/frp/frpc -c /data/frp/frpc.toml >> /data/frp/log.txt 2>&1 &
    ;;
  stop)
    killall frpc
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac
exit 0